name: catbreets
description: "App for see all about cats"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  bloc: ^8.1.4
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.0
  go_router: ^14.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/

flutter_native_splash:
  color: "#2196F3"
  branding: assets/icons/cat-5.png
  branding_android: assets/icons/cat-5.png
  branding_ios: assets/icons/cat-5.png
  branding_mode: bottom